name: "Go Test"

on: ["push"]

jobs:
  go:
    runs-on: ubuntu-latest
    name: Go
    services:
      mariadb:
        image: mariadb:latest
        ports:
          - 3306:3306
        env:
          MYSQL_USER: user
          MYSQL_PASSWORD: password
          MYSQL_DATABASE: test
          MYSQL_ROOT_PASSWORD: password
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3
    steps:
      - name: Install Go
        if: success()
        uses: actions/setup-go@v1
        with:
          go-version: 1.15.x
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Download go-assets-builder
        run: |
          go get -u github.com/jessevdk/go-assets-builder
          echo $(go env GOPATH)/bin >> $GITHUB_PATH
      - name: Copy .env file
        run: cp .github/.env .env
      - name: Build static files
        run: make build
      - name: Test
        run: make github-test
